const express=require('express'),path=require('path'),app=express();
app.use(express.static('public'));app.use(express.json());
app.get('/',(r,s)=>s.sendFile(path.join(__dirname,'index.html')));
app.get('/work/qluve-eldercare-robotics',(r,s)=>s.sendFile(path.join(__dirname,'public/work/qluve-eldercare-robotics/index.html')));
app.get('/ai-product-studio',(r,s)=>s.sendFile(path.join(__dirname,'public/ai-product-studio/index.html')));
app.post('/api/signup',(r,s)=>{console.log('Signup:',r.body);s.json({success:true})});
app.post('/api/analytics',(r,s)=>s.json({success:true}));
app.get('/success',(r,s)=>s.send('<html><body style="display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:sans-serif"><div style="text-align:center"><h1>Thank you!</h1><p>Purchase successful.</p><a href="/">Go back</a></div></body></html>'));
app.get('/sitemap.xml',(r,s)=>{s.type('application/xml');s.send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://ilu-space.madmantra.app/</loc><changefreq>weekly</changefreq><priority>1.0</priority></url><url><loc>https://ilu-space.madmantra.app/ai-product-studio</loc><changefreq>monthly</changefreq><priority>0.9</priority></url><url><loc>https://ilu-space.madmantra.app/work/qluve-eldercare-robotics</loc><changefreq>monthly</changefreq><priority>0.8</priority></url></urlset>`);});
const PORT=process.env.PORT||3000;app.listen(PORT,()=>console.log('Running on '+PORT));
